### ISSUE TITLE
issue with meson on raspian buster

### ISSUE THREAD

**Issue by tlosm** [mikehooper/PiScripts#1]
The issue:
meson.build:21:0: ERROR:  Meson version is 0.49.2 but project requires >= 0.52.
 
Look like there is no official build of meson 0.52 on buster

>pip3 install meson
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: meson in /usr/lib/python3/dist-packages (0.49.2)

>uname -a
Linux raspberrypi 5.4.47-v7l+ #1322 SMP Wed Jun 17 17:58:52 BST 2020 armv7l GNU/Linux

>cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**Comment by mikehooper** [comment]
On the latest Raspberry Pi OS 32 fully updated, I get:

```
pip3 install meson
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: meson in ./.local/lib/python3.7/site-packages (0.54.2)

```

Do you need to uninstall then install ?

Edit1: or maybe: pip3 install 'meson>0.54.0'

Edit2: even better: pip3 install meson --force-reinstall

**Comment by mikehooper** [comment]
Updated script to force meson reinstall
